#Particle
/gun/particle mu+
/gun/energy 4 GeV

#World
/world/xWorld 0.06
/world/yWorld 0.06
/world/zWorld 0.06

#Detector
/detector/xDet 0.012
/detector/yDet 0.012
#nCols*nRows=numOfPixels
/detector/nCols 10
/detector/nRows 10

#Aerogel
/aerogel/xAerogel 0.02
/aerogel/yAerogel 0.02
/aerogel/zAerogel 0.005
/aerogel/dAerogel 0.04
/aerogel/rAerogel 1.1

#Materials
/materials/mRadiator 2
#1=water,2=aerogel
/materials/mWorld 3
#3=air


#Run
/run/initialize
/run/reinitializeGeometry
/run/beamOn 1
